StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{671D353F589D6936}" {
   Id "Jamahiriya-Anti-Tank"
   Target_en_us "Anti-Tank"
   Modified 1729970323
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D6937}" {
   Id "Jamahiriya-Assistant_Anti-Tank"
   Target_en_us "Assistant Anti-Tank"
   Modified 1729970324
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D217732912DD6}" {
   Id "Jamahiriya-Faction_UI_Name"
   Target_en_us "Jamahiriya Army"
   Modified 1730088169
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE61D}" {
   Id "Jamahiriya-Faction_UI_Name_Upper"
   Target_en_us "LIBYAN ARAB JAMAHIRIYA ARMY"
   Modified 1729963679
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D6932}" {
   Id "Jamahiriya-Grenadier"
   Target_en_us "Grenadier"
   Modified 1729970319
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D6934}" {
   Id "Jamahiriya-Heavy_Machine_Gunner"
   Target_en_us "Heavy Machine Gunner"
   Modified 1729970321
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D6933}" {
   Id "Jamahiriya-Light_Machine_Gunner"
   Target_en_us "Light Machine Gunner"
   Modified 1729970320
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D6935}" {
   Id "Jamahiriya-Machine_Gunner_Assistant"
   Target_en_us "Machine Gunner Assistant"
   Modified 1729970322
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D6938}" {
   Id "Jamahiriya-Marksman"
   Target_en_us "Marksman"
   Modified 1729970325
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D6931}" {
   Id "Jamahiriya-Medic"
   Target_en_us "Medic"
   Modified 1729970318
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D6930}" {
   Id "Jamahiriya-Rifleman"
   Target_en_us "Rifleman"
   Modified 1729970317
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D692F}" {
   Id "Jamahiriya-Squad_Leader"
   Target_en_us "Squad Leader"
   Modified 1729970316
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEF6A1B}" {
   Id "Libya-Callsign_Adel"
   Target_en_us "Adel"
   Modified 1729970829
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEF6A17}" {
   Id "Libya-Callsign_Adel_UC"
   Target_en_us "ADEL"
   Modified 1729970869
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEC9DE9}" {
   Id "Libya-Callsign_Amin"
   Target_en_us "Amin"
   Modified 1729970839
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEC9DE5}" {
   Id "Libya-Callsign_Amin_UC"
   Target_en_us "AMIN"
   Modified 1729970879
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEE80C3}" {
   Id "Libya-Callsign_Anwar"
   Target_en_us "Anwar"
   Modified 1729970824
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEE80BF}" {
   Id "Libya-Callsign_Anwar_UC"
   Target_en_us "ANWAR"
   Modified 1729970864
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE07F6B}" {
   Id "Libya-Callsign_Asad"
   Target_en_us "Asad"
   Modified 1729970800
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE07F6C}" {
   Id "Libya-Callsign_Asad_UC"
   Target_en_us "ASAD"
   Modified 1729970840
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEFF3B6}" {
   Id "Libya-Callsign_Aziz"
   Target_en_us "Aziz"
   Modified 1729970832
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEFF3B2}" {
   Id "Libya-Callsign_Aziz_UC"
   Target_en_us "AZIZ"
   Modified 1729970872
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEE80C0}" {
   Id "Libya-Callsign_Bassam"
   Target_en_us "Bassam"
   Modified 1729970825
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEE80BC}" {
   Id "Libya-Callsign_Bassam_UC"
   Target_en_us "BASSAM"
   Modified 1729970865
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE109FA}" {
   Id "Libya-Callsign_Bedouin"
   Target_en_us "Bedouin"
   Modified 1729970806
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE109F6}" {
   Id "Libya-Callsign_Bedouin_UC"
   Target_en_us "BEDOUIN"
   Modified 1729970846
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE07F5C}" {
   Id "Libya-Callsign_Fahd"
   Target_en_us "Fahd"
   Modified 1729970803
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE07F5F}" {
   Id "Libya-Callsign_Fahd_UC"
   Target_en_us "FAHD"
   Modified 1729970843
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE14B74}" {
   Id "Libya-Callsign_Faisal"
   Target_en_us "Faisal"
   Modified 1729970815
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE14B70}" {
   Id "Libya-Callsign_Faisal_UC"
   Target_en_us "FAISAL"
   Modified 1729970855
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEC3FD2}" {
   Id "Libya-Callsign_Farid"
   Target_en_us "Farid"
   Modified 1729970835
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEC3FCE}" {
   Id "Libya-Callsign_Farid_UC"
   Target_en_us "FARID"
   Modified 1729970875
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE109FB}" {
   Id "Libya-Callsign_Gamal"
   Target_en_us "Gamal"
   Modified 1729970807
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE109F7}" {
   Id "Libya-Callsign_Gamal_UC"
   Target_en_us "GAMAL"
   Modified 1729970847
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE109F8}" {
   Id "Libya-Callsign_Hakim"
   Target_en_us "Hakim"
   Modified 1729970808
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE109F4}" {
   Id "Libya-Callsign_Hakim_UC"
   Target_en_us "HAKIM"
   Modified 1729970848
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEEA2EB}" {
   Id "Libya-Callsign_Hamza"
   Target_en_us "Hamza"
   Modified 1729970823
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEEA2E7}" {
   Id "Libya-Callsign_Hamza_UC"
   Target_en_us "HAMZA"
   Modified 1729970863
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE1D16D}" {
   Id "Libya-Callsign_Hasan"
   Target_en_us "Hasan"
   Modified 1729970817
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE1D169}" {
   Id "Libya-Callsign_Hasan_UC"
   Target_en_us "HASAN"
   Modified 1729970857
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEF6A1A}" {
   Id "Libya-Callsign_Jamal"
   Target_en_us "Jamal"
   Modified 1729970830
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEF6A16}" {
   Id "Libya-Callsign_Jamal_UC"
   Target_en_us "JAMAL"
   Modified 1729970870
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE14B75}" {
   Id "Libya-Callsign_Jamil"
   Target_en_us "Jamil"
   Modified 1729970814
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE14B71}" {
   Id "Libya-Callsign_Jamil_UC"
   Target_en_us "JAMIL"
   Modified 1729970854
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEC5675}" {
   Id "Libya-Callsign_Jawad"
   Target_en_us "Jawad"
   Modified 1729970836
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEC5671}" {
   Id "Libya-Callsign_Jawad_UC"
   Target_en_us "JAWAD"
   Modified 1729970876
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE109F9}" {
   Id "Libya-Callsign_Karim"
   Target_en_us "Karim"
   Modified 1729970809
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE109F5}" {
   Id "Libya-Callsign_Karim_UC"
   Target_en_us "KARIM"
   Modified 1729970849
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEE14D0}" {
   Id "Libya-Callsign_Khalid"
   Target_en_us "Khalid"
   Modified 1729970818
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEE14CC}" {
   Id "Libya-Callsign_Khalid_UC"
   Target_en_us "KHALID"
   Modified 1729970858
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEC3FD1}" {
   Id "Libya-Callsign_Majid"
   Target_en_us "Majid"
   Modified 1729970834
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEC3FCD}" {
   Id "Libya-Callsign_Majid_UC"
   Target_en_us "MAJID"
   Modified 1729970874
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE15525}" {
   Id "Libya-Callsign_Malik"
   Target_en_us "Malik"
   Modified 1729970810
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE15521}" {
   Id "Libya-Callsign_Malik_UC"
   Target_en_us "MALIK"
   Modified 1729970850
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEF6A1C}" {
   Id "Libya-Callsign_Mustafa"
   Target_en_us "Mustafa"
   Modified 1729970828
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEF6A18}" {
   Id "Libya-Callsign_Mustafa_UC"
   Target_en_us "MUSTAFA"
   Modified 1729970868
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEF2C79}" {
   Id "Libya-Callsign_Nabil"
   Target_en_us "Nabil"
   Modified 1729970827
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEF2C75}" {
   Id "Libya-Callsign_Nabil_UC"
   Target_en_us "NABIL"
   Modified 1729970867
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE08C9A}" {
   Id "Libya-Callsign_Nasr"
   Target_en_us "Nasr"
   Modified 1729970804
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE08C9B}" {
   Id "Libya-Callsign_Nasr_UC"
   Target_en_us "NASR"
   Modified 1729970844
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEFF3B5}" {
   Id "Libya-Callsign_Nasser"
   Target_en_us "Nasser"
   Modified 1729970831
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEFF3B1}" {
   Id "Libya-Callsign_Nasser_UC"
   Target_en_us "NASSER"
   Modified 1729970871
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE07F5A}" {
   Id "Libya-Callsign_Nimer"
   Target_en_us "Nimer"
   Modified 1729970801
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE07F5D}" {
   Id "Libya-Callsign_Nimer_UC"
   Target_en_us "NIMER"
   Modified 1729970841
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEFF3B7}" {
   Id "Libya-Callsign_Radi"
   Target_en_us "Radi"
   Modified 1729970833
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEFF3B3}" {
   Id "Libya-Callsign_Radi_UC"
   Target_en_us "RADI"
   Modified 1729970873
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEF2C78}" {
   Id "Libya-Callsign_Rahim"
   Target_en_us "Rahim"
   Modified 1729970826
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEF2C74}" {
   Id "Libya-Callsign_Rahim_UC"
   Target_en_us "RAHIM"
   Modified 1729970866
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEE132A}" {
   Id "Libya-Callsign_Rami"
   Target_en_us "Rami"
   Modified 1729970820
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEE1326}" {
   Id "Libya-Callsign_Rami_UC"
   Target_en_us "RAMI"
   Modified 1729970860
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE15522}" {
   Id "Libya-Callsign_Rashid"
   Target_en_us "Rashid"
   Modified 1729970811
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE1551E}" {
   Id "Libya-Callsign_Rashid_UC"
   Target_en_us "RASHID"
   Modified 1729970851
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEC5676}" {
   Id "Libya-Callsign_Safwan"
   Target_en_us "Safwan"
   Modified 1729970837
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEC5672}" {
   Id "Libya-Callsign_Safwan_UC"
   Target_en_us "SAFWAN"
   Modified 1729970877
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE08CCB}" {
   Id "Libya-Callsign_Sahara"
   Target_en_us "Sahara"
   Modified 1729970805
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE08CCA}" {
   Id "Libya-Callsign_Sahara_UC"
   Target_en_us "SAHARA"
   Modified 1729970845
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE14B71}" {
   Id "Libya-Callsign_Salah"
   Target_en_us "Salah"
   Modified 1729970816
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE14B6D}" {
   Id "Libya-Callsign_Salah_UC"
   Target_en_us "SALAH"
   Modified 1729970856
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEEA2ED}" {
   Id "Libya-Callsign_Samir"
   Target_en_us "Samir"
   Modified 1729970821
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEEA2E9}" {
   Id "Libya-Callsign_Samir_UC"
   Target_en_us "SAMIR"
   Modified 1729970861
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE07F5B}" {
   Id "Libya-Callsign_Saqr"
   Target_en_us "Saqr"
   Modified 1729970802
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE07F5E}" {
   Id "Libya-Callsign_Saqr_UC"
   Target_en_us "SAQR"
   Modified 1729970842
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE15523}" {
   Id "Libya-Callsign_Tariq"
   Target_en_us "Tariq"
   Modified 1729970812
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE1551F}" {
   Id "Libya-Callsign_Tariq_UC"
   Target_en_us "TARIQ"
   Modified 1729970852
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEEA2EA}" {
   Id "Libya-Callsign_Walid"
   Target_en_us "Walid"
   Modified 1729970822
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEEA2E6}" {
   Id "Libya-Callsign_Walid_UC"
   Target_en_us "WALID"
   Modified 1729970862
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEE132B}" {
   Id "Libya-Callsign_Yusuf"
   Target_en_us "Yusuf"
   Modified 1729970819
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEE1327}" {
   Id "Libya-Callsign_Yusuf_UC"
   Target_en_us "YUSUF"
   Modified 1729970859
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE14B76}" {
   Id "Libya-Callsign_Zaid"
   Target_en_us "Zaid"
   Modified 1729970813
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DE14B72}" {
   Id "Libya-Callsign_Zaid_UC"
   Target_en_us "ZAID"
   Modified 1729970853
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEC5666}" {
   Id "Libya-Callsign_Zaki"
   Target_en_us "Zaki"
   Modified 1729970838
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353E4DEC5662}" {
   Id "Libya-Callsign_Zaki_UC"
   Target_en_us "ZAKI"
   Modified 1729970878
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A9D8B7}" {
   Id "Libya-Territory_Ajdabiya"
   Target_en_us "Ajdabiya"
   Modified 1729970712
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A6D17E}" {
   Id "Libya-Territory_Bani_Walid"
   Target_en_us "Bani Walid"
   Modified 1729970724
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A8609E}" {
   Id "Libya-Territory_Bayda"
   Target_en_us "Bayda"
   Modified 1729970708
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A8B5CE}" {
   Id "Libya-Territory_Benghazi"
   Target_en_us "Benghazi"
   Modified 1729970701
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A93438}" {
   Id "Libya-Territory_Brega"
   Target_en_us "Brega"
   Modified 1729970713
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A8609C}" {
   Id "Libya-Territory_Derna"
   Target_en_us "Derna"
   Modified 1729970707
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A6907C}" {
   Id "Libya-Territory_Ghadames"
   Target_en_us "Ghadames"
   Modified 1729970718
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A9F12A}" {
   Id "Libya-Territory_Gharyan"
   Target_en_us "Gharyan"
   Modified 1729970709
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A91089}" {
   Id "Libya-Territory_Ghat"
   Target_en_us "Ghat"
   Modified 1729970714
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A9F12C}" {
   Id "Libya-Territory_Khoms"
   Target_en_us "Khoms"
   Modified 1729970710
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A978B2}" {
   Id "Libya-Territory_Kufra"
   Target_en_us "Kufra"
   Modified 1729970717
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A6FD86}" {
   Id "Libya-Territory_Marj"
   Target_en_us "Marj"
   Modified 1729970720
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A8B5F0}" {
   Id "Libya-Territory_Misrata"
   Target_en_us "Misrata"
   Modified 1729970702
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A910B5}" {
   Id "Libya-Territory_Murzuq"
   Target_en_us "Murzuq"
   Modified 1729970716
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A6907A}" {
   Id "Libya-Territory_Nalut"
   Target_en_us "Nalut"
   Modified 1729970719
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A86092}" {
   Id "Libya-Territory_Sabha"
   Target_en_us "Sabha"
   Modified 1729970706
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A6FD84}" {
   Id "Libya-Territory_Sabratha"
   Target_en_us "Sabratha"
   Modified 1729970721
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A8CEED}" {
   Id "Libya-Territory_Sirte"
   Target_en_us "Sirte"
   Modified 1729970703
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A6FD95}" {
   Id "Libya-Territory_Tarhuna"
   Target_en_us "Tarhuna"
   Modified 1729970723
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A86072}" {
   Id "Libya-Territory_Tobruk"
   Target_en_us "Tobruk"
   Modified 1729970705
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A8B5CD}" {
   Id "Libya-Territory_Tripoli"
   Target_en_us "Tripoli"
   Modified 1729970700
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A9108B}" {
   Id "Libya-Territory_Ubari"
   Target_en_us "Ubari"
   Modified 1729970715
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A8CEEA}" {
   Id "Libya-Territory_Zawiya"
   Target_en_us "Zawiya"
   Modified 1729970704
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A9D8A3}" {
   Id "Libya-Territory_Zliten"
   Target_en_us "Zliten"
   Modified 1729970711
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671EA7DE26A6FD8A}" {
   Id "Libya-Territory_Zuwara"
   Target_en_us "Zuwara"
   Modified 1729970722
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{67211EC71E9AD15A}" {
   Id "Libyan-Deputy_Platoon_Leader"
   Target_en_us "Deputy Platoon Leader"
   Modified 1730229811
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{67211EC7BED786E8}" {
   Id "Libyan-Platoon_Command"
   Target_en_us "Platoon Command Section"
   Modified 1730229728
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{67211EC7416D1B05}" {
   Id "Libyan-Platoon_Leader"
   Target_en_us "Platoon Leader"
   Modified 1730229748
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE629}" {
   Id "Libyans-FirstName_Abdallah"
   Target_en_us "Abdallah"
   Modified 1729963691
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE61E}" {
   Id "Libyans-FirstName_Ahmed"
   Target_en_us "Ahmed"
   Modified 1729963680
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE623}" {
   Id "Libyans-FirstName_Ali"
   Target_en_us "Ali"
   Modified 1729963685
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE633}" {
   Id "Libyans-FirstName_Bilal"
   Target_en_us "Bilal"
   Modified 1729963701
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE632}" {
   Id "Libyans-FirstName_Farouk"
   Target_en_us "Farouk"
   Modified 1729963700
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE62D}" {
   Id "Libyans-FirstName_Fathi"
   Target_en_us "Fathi"
   Modified 1729963695
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE630}" {
   Id "Libyans-FirstName_Hamza"
   Target_en_us "Hamza"
   Modified 1729963698
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE624}" {
   Id "Libyans-FirstName_Hassan"
   Target_en_us "Hassan"
   Modified 1729963686
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE625}" {
   Id "Libyans-FirstName_Ibrahim"
   Target_en_us "Ibrahim"
   Modified 1729963687
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE62E}" {
   Id "Libyans-FirstName_Jamal"
   Target_en_us "Jamal"
   Modified 1729963696
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE62A}" {
   Id "Libyans-FirstName_Karim"
   Target_en_us "Karim"
   Modified 1729963692
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE621}" {
   Id "Libyans-FirstName_Khalid"
   Target_en_us "Khalid"
   Modified 1729963683
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE62C}" {
   Id "Libyans-FirstName_Mahmoud"
   Target_en_us "Mahmoud"
   Modified 1729963694
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE61F}" {
   Id "Libyans-FirstName_Mohammed"
   Target_en_us "Mohammed"
   Modified 1729963681
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE622}" {
   Id "Libyans-FirstName_Mustafa"
   Target_en_us "Mustafa"
   Modified 1729963684
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE62F}" {
   Id "Libyans-FirstName_Nabil"
   Target_en_us "Nabil"
   Modified 1729963697
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE620}" {
   Id "Libyans-FirstName_Omar"
   Target_en_us "Omar"
   Modified 1729963682
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE631}" {
   Id "Libyans-FirstName_Rashid"
   Target_en_us "Rashid"
   Modified 1729963699
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE62B}" {
   Id "Libyans-FirstName_Saleh"
   Target_en_us "Saleh"
   Modified 1729963693
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE627}" {
   Id "Libyans-FirstName_Samir"
   Target_en_us "Samir"
   Modified 1729963689
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE628}" {
   Id "Libyans-FirstName_Tariq"
   Target_en_us "Tariq"
   Modified 1729963690
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE634}" {
   Id "Libyans-FirstName_Walid"
   Target_en_us "Walid"
   Modified 1729963702
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE626}" {
   Id "Libyans-FirstName_Youssef"
   Target_en_us "Youssef"
   Modified 1729963688
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE64A}" {
   Id "Libyans-Surname_AlBarghathi"
   Target_en_us "Al-Barghathi"
   Modified 1729963724
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE643}" {
   Id "Libyans-Surname_AlFaraj"
   Target_en_us "Al-Faraj"
   Modified 1729963717
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE635}" {
   Id "Libyans-Surname_AlGaddafi"
   Target_en_us "Al-Gaddafi"
   Modified 1729963703
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE63E}" {
   Id "Libyans-Surname_AlHadi"
   Target_en_us "Al-Hadi"
   Modified 1729963712
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE646}" {
   Id "Libyans-Surname_AlKadhafi"
   Target_en_us "Al-Kadhafi"
   Modified 1729963720
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE636}" {
   Id "Libyans-Surname_AlMabrouk"
   Target_en_us "Al-Mabrouk"
   Modified 1729963704
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE63A}" {
   Id "Libyans-Surname_AlMegrahi"
   Target_en_us "Al-Megrahi"
   Modified 1729963708
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE637}" {
   Id "Libyans-Surname_AlSharif"
   Target_en_us "Al-Sharif"
   Modified 1729963705
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE640}" {
   Id "Libyans-Surname_AlZawi"
   Target_en_us "Al-Zawi"
   Modified 1729963714
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE639}" {
   Id "Libyans-Surname_Benali"
   Target_en_us "Benali"
   Modified 1729963707
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE63D}" {
   Id "Libyans-Surname_Benghazi"
   Target_en_us "Benghazi"
   Modified 1729963711
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE642}" {
   Id "Libyans-Surname_Bouzid"
   Target_en_us "Bouzid"
   Modified 1729963716
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE648}" {
   Id "Libyans-Surname_ElGerbi"
   Target_en_us "El-Gerbi"
   Modified 1729963722
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE63C}" {
   Id "Libyans-Surname_ElSharif"
   Target_en_us "El-Sharif"
   Modified 1729963710
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE638}" {
   Id "Libyans-Surname_ElWarfalli"
   Target_en_us "El-Warfalli"
   Modified 1729963706
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE647}" {
   Id "Libyans-Surname_Fezzani"
   Target_en_us "Fezzani"
   Modified 1729963721
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE641}" {
   Id "Libyans-Surname_Khamis"
   Target_en_us "Khamis"
   Modified 1729963715
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE63B}" {
   Id "Libyans-Surname_Mansour"
   Target_en_us "Mansour"
   Modified 1729963709
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE649}" {
   Id "Libyans-Surname_Misrati"
   Target_en_us "Misrati"
   Modified 1729963723
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE645}" {
   Id "Libyans-Surname_Najjar"
   Target_en_us "Najjar"
   Modified 1729963719
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE64B}" {
   Id "Libyans-Surname_Sabratha"
   Target_en_us "Sabratha"
   Modified 1729963725
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE63F}" {
   Id "Libyans-Surname_Trabelsi"
   Target_en_us "Trabelsi"
   Modified 1729963713
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D2174242BE644}" {
   Id "Libyans-Surname_Tripoli"
   Target_en_us "Tripoli"
   Modified 1729963718
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D693E}" {
   Id "Ntc-Anti-Tank"
   Target_en_us "Anti-Tank"
   Modified 1729970331
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F4639C7CE}" {
   Id "Ntc-Faction_UI_Name"
   Target_en_us "NTC"
   Modified 1729970308
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D692E}" {
   Id "Ntc-Faction_UI_Name_Upper"
   Target_en_us "NTC"
   Modified 1729970315
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D693C}" {
   Id "Ntc-Grenadier"
   Target_en_us "Grenadier"
   Modified 1729970329
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D693D}" {
   Id "Ntc-Heavy_Machine_Gunner"
   Target_en_us "Heavy Machine Gunner"
   Modified 1729970330
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D693F}" {
   Id "Ntc-Marksman"
   Target_en_us "Marksman"
   Modified 1729970332
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D693B}" {
   Id "Ntc-Medic"
   Target_en_us "Medic"
   Modified 1729970328
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D693A}" {
   Id "Ntc-Rifleman"
   Target_en_us "Rifleman"
   Modified 1729970327
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{671D353F589D6939}" {
   Id "Ntc-Squad_Leader"
   Target_en_us "Squad Leader"
   Modified 1729970326
   Author "siwi1"
   LastChanged "siwi1"
  }
 }
}