SCR_PlaceableEntitiesRegistry {
 m_sAddon "LibyanCivilWar2011Factions"
 m_sSourceDirectory "{AFEEC9439F3D8DB5}Prefabs/Characters/Factions/BLUFOR/Ntc_Army"
 m_bExposed 1
 m_Prefabs {
  "{7165375344E0F689}Prefabs/Characters/Factions/BLUFOR/Ntc_Army/Character_NtcBLUFOR_AT.et"
  "{D11D5FC63D096D36}Prefabs/Characters/Factions/BLUFOR/Ntc_Army/Character_NtcBLUFOR_Grenadier1.et"
  "{BD496B2681CDE218}Prefabs/Characters/Factions/BLUFOR/Ntc_Army/Character_NtcBLUFOR_Grenadier2.et"
  "{FBDA80885326FC36}Prefabs/Characters/Factions/BLUFOR/Ntc_Army/Character_NtcBLUFOR_HMG.et"
  "{BA40BD8C5545FEB2}Prefabs/Characters/Factions/BLUFOR/Ntc_Army/Character_NtcBLUFOR_Marksman.et"
  "{F0B19FED6F625B51}Prefabs/Characters/Factions/BLUFOR/Ntc_Army/Character_NtcBLUFOR_Medic.et"
  "{E8FB40DFDDC533A5}Prefabs/Characters/Factions/BLUFOR/Ntc_Army/Character_NtcBLUFOR_Rifleman1.et"
  "{3ED613C3E928A51B}Prefabs/Characters/Factions/BLUFOR/Ntc_Army/Character_NtcBLUFOR_Rifleman2.et"
  "{DB4A5F3AE5CD3270}Prefabs/Characters/Factions/BLUFOR/Ntc_Army/Character_NtcBLUFOR_Rifleman3.et"
  "{C445AF8D0FED4AC6}Prefabs/Characters/Factions/BLUFOR/Ntc_Army/Character_NtcBLUFOR_SL.et"
  "{5D5B1614120A7B56}Prefabs/Characters/Factions/BLUFOR/Ntc_Army/Character_NtcBLUFOR_PL.et"
  "{F32A2CC3698954FD}Prefabs/Characters/Factions/BLUFOR/Ntc_Army/Character_NtcBLUFOR_DPL.et"
 }
}