SCR_PlaceableEntitiesRegistry {
 m_sAddon "LibyanCivilWar2011Factions"
 m_sSourceDirectory "{54A9D61CD8F3160D}Prefabs/Groups/BLUFOR"
 m_bExposed 1
 m_Prefabs {
  "{E370A1282E9537D1}Prefabs/Groups/BLUFOR/Group_NtcBLUFOR_RifleSquad.et"
  "{12CCF437790F3AC7}Prefabs/Groups/BLUFOR/Group_NtcBLUFOR_PlatoonCommand.et"
 }
}