EditablePrefabsComponent_EditableEntity {
 m_EntityLabelRules {
  EditablePrefabsLabel_Faction "{671D35308EF0DD26}" {
   m_Label FACTION_JAMAHIRIYA_OPFOR
   m_FactionToCheck "JamahiriyaOPFOR"
  }
  EditablePrefabsLabel_Faction "{671D35304076709A}" {
   m_Label FACTION_NTC_BLUFOR
   m_FactionToCheck "NtcBLUFOR"
  }
 }
}