SCR_PlaceableEntitiesRegistry {
 m_sAddon "LibyanCivilWar2011Factions"
 m_sSourceDirectory "{DCF44154CA43E359}PrefabsEditable/System"
 m_Prefabs {
  "{CBFC637EBD7BC3E8}PrefabsEditable/SpawnPoints/E_SpawnPoint_NtcBLUFOR.et"
  "{0E37C12035170A3B}PrefabsEditable/SpawnPoints/E_SpawnPoint_JamahiriyaOPFOR.et"
 }
}