SCR_PlaceableEntitiesRegistry {
 m_sAddon "LibyanCivilWar2011Factions"
 m_sSourceDirectory "{FE76DC01BBBAE9CD}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army"
 m_bExposed 1
 m_Prefabs {
  "{01D1376503155548}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_AAT.et"
  "{9FE6FB6D53EB9891}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_AT.et"
  "{6B45895C35F7BCED}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_Grenadier.et"
  "{5106BF9F8399C349}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_HMG.et"
  "{463683C34ED2392C}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_LMG.et"
  "{B82BEEC3C1D50037}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_Marksman.et"
  "{211DC9CAA8D995F4}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_Medic.et"
  "{FBC01AF08CEAB1D1}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_MGA.et"
  "{EA9013904955CD20}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_Rifleman.et"
  "{2AC663B318E624DE}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_SL.et"
  "{CED76DE695694A86}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_DPL.et"
  "{B3D8DA2A0501154E}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_PL.et"
  "{02AA992B8E40095A}Prefabs/Characters/Factions/OPFOR/Jamahiriya_Army/Character_JamahiriyaOPFOR_Crewman.et"
 }
}