SCR_PlaceableEntitiesRegistry {
 m_sAddon "LibyanCivilWar2011Factions"
 m_sSourceDirectory "{3EC6BA86CF7B0DD0}Prefabs/Groups/OPFOR"
 m_bExposed 1
 m_Prefabs {
  "{C33D083E9C68B874}Prefabs/Groups/OPFOR/Group_JamahiriyaOPFOR_RifleSquad.et"
  "{7D0DF3C5CA2AD495}Prefabs/Groups/OPFOR/Group_JamahiriyaOPFOR_PlatoonCommand.et"
 }
}