SCR_PlaceableEntitiesRegistry {
 m_sAddon "LibyanCivilWar2011Factions"
 m_sSourceDirectory "{3A4DC29454786A92}Prefabs/Vehicles/JamahiriyaOPFOR"
 m_Prefabs {
  "{EDC5374B5E649199}Prefabs/Vehicles/JamahiriyaOPFOR/S1203_cargo_beige_ambulance.et"
  "{FA410F8C2B4F0B52}Prefabs/Vehicles/JamahiriyaOPFOR/M113A2_APC_Jam.et"
  "{E689318F80F144E0}Prefabs/Vehicles/NtcBLUFOR/3Series_Libyan_M2HB_Variant_2.et"
  "{D016486BFF4E4C24}Prefabs/Vehicles/JamahiriyaOPFOR/Ural4320_ammo_JamahiriyaOPFOR.et"
 }
}