SCR_PlaceableEntitiesRegistry {
 m_sAddon "LibyanCivilWar2011Factions"
 m_sSourceDirectory "{A5870E6BBE3D57FC}Prefabs/Vehicles/NtcBLUFOR"
 m_Prefabs {
  "{A86E788EF1809C3A}Prefabs/Vehicles/NtcBLUFOR/Ural4320_ammo_NtcBlufor.et"
  "{EE315F09F08ACB27}Prefabs/Vehicles/NtcBLUFOR/S1203_cargo_white_ambulance.et"
  "{3EB62AE53E4AF63F}Prefabs/Vehicles/NtcBLUFOR/M113A2_APC.et"
  "{00F7ACA22D68E815}Prefabs/Vehicles/NtcBLUFOR/3Series_Libyan_M2HB_Variant_2.et"
  "{7751D85554E40A97}Prefabs/Vehicles/NtcBLUFOR/3Series_ZU.et"
 }
}