SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{671D3532572A5FBD}" {
   m_Info SCR_UIInfo "{671D353239BC8CF3}" {
    Name "Jamahiriya Arab Army"
    Description "Armed Forces of the Libyan Arab Jamahiriya"
    Icon "{BF88289C313F0253}Assets/Icons/Jamahiriya_Icon.edds"
   }
   m_LabelType FACTION_JAMAHIRIYA_OPFOR
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{671D35338AF05CF4}" {
   m_Info SCR_UIInfo "{671D353339A08285}" {
    Name "NTC Forces"
    Description "National Transitional Council Forces"
    Icon "{DC7AE4D370872189}Assets/Icons/Ntc_Icon.edds"
   }
   m_LabelType FACTION_NTC_BLUFOR
   m_LabelGroupType FACTION
  }
 }
}